version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: honeypot-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - bootstrap.memory_lock=true
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - honeypot-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 256M

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.0
    container_name: honeypot-logstash
    volumes:
      - ./elk-stack/logstash/pipeline:/usr/share/logstash/pipeline
      - ./elk-stack/logstash/config:/usr/share/logstash/config
      - ./logs:/logs
    ports:
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx128m -Xms128m"
      PIPELINE_WORKERS: 1
      PIPELINE_BATCH_SIZE: 125
    networks:
      - honeypot-network
    depends_on:
      - elasticsearch
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 150M
        reservations:
          memory: 128M

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.0
    container_name: honeypot-kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      NODE_OPTIONS: "--max-old-space-size=256"
      LOGGING_QUIET: true
    networks:
      - honeypot-network
    depends_on:
      - elasticsearch
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 150M

  redis:
    image: redis:7-alpine
    container_name: honeypot-redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 50mb --maxmemory-policy allkeys-lru
    networks:
      - honeypot-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M

volumes:
  elasticsearch_data:
    driver: local

networks:
  honeypot-network:
    driver: bridge