version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: honeypot-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - honeypot-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.0
    container_name: honeypot-logstash
    volumes:
      - ./elk-stack/logstash/pipeline:/usr/share/logstash/pipeline
      - ./elk-stack/logstash/config:/usr/share/logstash/config
      - ./logs:/logs
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - honeypot-network
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.0
    container_name: honeypot-kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - honeypot-network
    depends_on:
      - elasticsearch

  redis:
    image: redis:7-alpine
    container_name: honeypot-redis
    ports:
      - "6379:6379"
    networks:
      - honeypot-network

volumes:
  elasticsearch_data:
    driver: local

networks:
  honeypot-network:
    driver: bridge