honeypot:
  ssh:
    enabled: true
    port: 2222  # Keep this as it matches your security group
    banner: "SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.4"
    max_connections: 200  # Increased for cloud environment
    timeout: 30
    fake_users:  # Keep your existing fake users
      - username: "admin"
        password: "admin"
      - username: "root"
        password: "password"
      - username: "user"
        password: "123456"
      - username: "test"
        password: "test"
    
  http:
    enabled: true
    port: 80  # Changed to 80 to match security group
    server_name: "Apache/2.4.41 (Ubuntu)"
    fake_pages:  # Keep your existing fake pages
      - path: "/admin"
        template: "admin_login.html"
      - path: "/login"
        template: "login.html"
      - path: "/wp-admin"
        template: "wordpress_admin.html"
      - path: "/phpmyadmin"
        template: "phpmyadmin.html"
    
  ftp:
    enabled: true
    port: 21  # Changed to 21 to match security group
    banner: "220 ProFTPD 1.3.6 Server ready."
    anonymous_allowed: true
    fake_files:  # Keep your existing fake files
      - "readme.txt"
      - "config.conf"
      - "backup.sql"
      - "users.csv"
    
  telnet:
    enabled: true
    port: 23  # Changed to 23 to match security group
    banner: "Ubuntu 20.04.5 LTS"
    fake_users:  # Keep your existing fake users
      - username: "admin"
        password: "admin"
      - username: "cisco"
        password: "cisco"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "/var/log/honeypot/honeypot.log"  # Changed to standard Linux log location
  max_size: "50MB"  # Increased for cloud environment
  backup_count: 10  # Increased for cloud environment

elasticsearch:
  host: "172.31.91.179"  # Private IP of your ELK instance
  port: 9200
  index_prefix: "honeypot"
  bulk_size: 100  # Added for better ES performance
  flush_interval: 10  # Added (seconds)
  
geolocation:
  enabled: true
  database_path: "/opt/honeypot/data/GeoLite2-City.mmdb"  # Standardized path
  
alerts:
  enabled: true
  email:
    smtp_server: "email-smtp.us-east-1.amazonaws.com"  # AWS SES recommended
    smtp_port: 587
    username: ""  # Fill with AWS SES credentials
    password: ""
    recipients: []  # Add your email here
  thresholds:
    failed_logins_per_minute: 20  # Increased for cloud
    unique_ips_per_hour: 100  # Increased for cloud
    suspicious_commands: ["wget", "curl", "nc", "nmap", "sqlmap", "aws", "ec2"]

threat_intelligence:
  enabled: true
  sources:
    - "https://reputation.alienvault.com/reputation.data"
    - "https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt"
    - "https://www.binarydefense.com/banlist.txt"  # Added
  update_interval: 1800  # More frequent updates (30 minutes)

dashboard:
  host: "0.0.0.0"
  port: 3000  # Changed to match security group
  debug: false
  secret_key: "your-secret-key-change-this"  # Generate a strong one
  auth_required: true  # Added for security
  auth_username: "admin"  # Added
  auth_password: "change-this-password"  # Added
  
# New AWS-specific section
aws:
  region: "us-east-1"  # Match your region
  metadata_service: "http://169.254.169.254"  # For AWS metadata
  instance_id: "i-0ee69c23d3d58b2cf"  # Your honeypot instance ID
  tags:
    project: "honeypot"
    environment: "production"
