honeypot:
  ssh:
    enabled: true
    port: 2222
    interface: "0.0.0.0"  # Listen on all interfaces for AWS
    banner: "SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.4"
    max_connections: 50  # Reduced for free tier
    timeout: 30
    fake_users:
      - username: "admin"
        password: "admin"
      - username: "root"
        password: "password"
      - username: "user"
        password: "123456"
      - username: "test"
        password: "test"
      - username: "ubuntu"
        password: "ubuntu"
      - username: "pi"
        password: "raspberry"
    
  http:
    enabled: true
    port: 80  # Standard HTTP port for AWS
    interface: "0.0.0.0"
    server_name: "Apache/2.4.41 (Ubuntu)"
    max_connections: 50  # Reduced for free tier
    fake_pages:
      - path: "/admin"
        template: "admin_login.html"
      - path: "/login"
        template: "login.html"
      - path: "/wp-admin"
        template: "wordpress_admin.html"
      - path: "/phpmyadmin"
        template: "phpmyadmin.html"
      - path: "/cpanel"
        template: "cpanel.html"
      - path: "/webmail"
        template: "webmail.html"
    
  ftp:
    enabled: true
    port: 21  # Standard FTP port for AWS
    interface: "0.0.0.0"
    banner: "220 ProFTPD 1.3.6 Server ready."
    anonymous_allowed: true
    max_connections: 20  # Reduced for free tier
    fake_files:
      - "readme.txt"
      - "config.conf"
      - "backup.sql"
      - "users.csv"
      - "passwords.txt"
      - "database_backup.sql"
    
  telnet:
    enabled: true
    port: 23  # Standard Telnet port for AWS
    interface: "0.0.0.0"
    banner: "Ubuntu 20.04.5 LTS"
    max_connections: 20  # Reduced for free tier
    fake_users:
      - username: "admin"
        password: "admin"
      - username: "cisco"
        password: "cisco"
      - username: "root"
        password: "toor"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/honeypot.log"
  max_size: "5MB"  # Reduced for free tier storage
  backup_count: 3  # Reduced for free tier storage
  
  # ELK integration
  elasticsearch_enabled: true
  logstash_enabled: true

elasticsearch:
  host: "localhost"  # Will be updated to ELK instance private IP
  port: 9200
  index_prefix: "honeypot"
  timeout: 30
  max_retries: 3
  
logstash:
  host: "localhost"  # Will be updated to ELK instance private IP
  port: 5044
  timeout: 30
  
geolocation:
  enabled: true
  database_path: "data/GeoLite2-City.mmdb"
  
alerts:
  enabled: true
  email:
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: ""  # Configure with your email
    password: ""  # Configure with your app password
    recipients: []  # Add your email addresses
  thresholds:
    failed_logins_per_minute: 5  # Reduced for more sensitive alerting
    unique_ips_per_hour: 25  # Reduced for more sensitive alerting
    suspicious_commands: ["wget", "curl", "nc", "nmap", "sqlmap", "nikto", "dirb", "gobuster"]
  
  # Slack integration (optional)
  slack:
    enabled: false
    webhook_url: ""
    channel: "#security-alerts"

threat_intelligence:
  enabled: true
  sources:
    - "https://reputation.alienvault.com/reputation.data"
    - "https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt"
    - "https://www.spamhaus.org/drop/drop.txt"
  update_interval: 7200  # 2 hours (reduced frequency for free tier)
  cache_duration: 86400  # 24 hours

dashboard:
  host: "0.0.0.0"
  port: 12000  # Updated to match runtime port
  debug: false
  secret_key: "aws-honeypot-secret-key-change-this-in-production"
  
  # Performance optimizations for free tier
  max_recent_attacks: 100  # Limit memory usage
  update_interval: 10  # Update every 10 seconds instead of 5
  
performance:
  # Memory optimization settings
  max_log_entries_memory: 1000  # Limit in-memory log entries
  log_rotation_size: "5MB"
  max_concurrent_connections: 100  # Global limit across all services
  
  # CPU optimization
  worker_processes: 1  # Single worker for free tier
  thread_pool_size: 4  # Reduced thread pool
  
security:
  # Rate limiting
  rate_limit_enabled: true
  max_requests_per_minute: 60
  max_requests_per_hour: 1000
  
  # IP blocking
  auto_block_enabled: true
  block_threshold: 50  # Block after 50 failed attempts
  block_duration: 3600  # Block for 1 hour
  
  # Honeypot detection evasion
  response_delay_min: 0.5  # Minimum response delay in seconds
  response_delay_max: 2.0  # Maximum response delay in seconds
  
monitoring:
  # System monitoring
  memory_threshold: 85  # Alert when memory usage exceeds 85%
  disk_threshold: 80    # Alert when disk usage exceeds 80%
  cpu_threshold: 90     # Alert when CPU usage exceeds 90%
  
  # Health checks
  health_check_interval: 300  # Check every 5 minutes
  elasticsearch_health_check: true
  service_health_check: true